name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]   # <-- triggers PyPI publish on a GitHub Release

permissions:
  id-token: write        # needed for PyPI OIDC
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest flake8
      - run: flake8 || true
      - run: |
          if [ -d tests ]; then pytest -q; else echo "no tests"; fi

  publish:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install build
      - name: Build wheel and sdist
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
